# Generated by Django 2.2.12 on 2022-02-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20220211_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Husband'),
        ),
    ]
